### ISSUE TITLE
[Arbitrary Code Execution] Faking function stringify to inject malicious code into 'Any' serialization

### ISSUE THREAD

**Issue by roobscoob** [varvolta/threadman#2]
The "Any" serializer fully trusts the result of .toString() for objects that are not of `typeof object` or `typeof string`. Unfortunately for the "Any" serializer, all objects in JS can have their toString method modified by an attacker.

Given an attacker with full control of the arguments provided to threadman, the attacker can gain ACE.

Minimum viable prototype:
```js
function a() {}

a.toString = () => "console.log('Arbitrary Code Exec')";

// function can be anything
// arguments can be anything given `a` is placed *somewhere* inside, even nested.
new Thread(() => {}, [a])
```

**Comment by varvolta** [comment]
Can you please clarify in which line did you see the injection opportunity.  Is it line 36 in any.js? If it's 36 then I added a check for overridden 'toString' function. If an injection is done with assigning toString function then it can be checked with data.hasOwnProperty('toString'). Thanks.
